### ISSUE TITLE
Add support for psr/log v2 and v3

### ISSUE THREAD

**Issue by kdubuc** [laminas/laminas-di#49]
Can we add support for Psr LoggerInterface to v2 and v3 (```"psr/log": "^1.0|^2.0|^3.0"```) ?

Currently, only v1.1.4 is supported : 
https://github.com/laminas/laminas-di/blob/b9a53578117faeff91c59fa6902fd0add0a1a844/composer.json#L38

**Comment by Ocramius** [comment]
@kdubuc do send a patch attempting to upgrade to `^2`, then `^3`? I'm OK with supporting all 3, but we need to make sure we verify them individually too, before proceeding.

**Comment by tux-rampage** [comment]
This was addressed in #94
