### ISSUE TITLE
Update Coding Standard to v2

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-di#5]
There are a lot of new conventions that are not covered by the current phpcs ruleset of [zend-coding-standard](/zendframework/zend-coding-standard) (v1.x).

Some examples are (incomplete list):

- Whitespace after cast operators
- Whitespace after not operator (`!`)
- Whitespaces before and after ternary operators
- Trailing comma for the last element in array declarations

A new coding style and tooling is currently work in progress at zendframework/zend-coding-standard#5. When this PR is merged and v2 is released this zend-di should integrate it.

Depending on my availability, I'll perform the tests as suggested in the mentioned PR.

---

Originally posted by @tux-rampage at https://github.com/zendframework/zend-di/issues/39

**Comment by gennadigennadigennadi** [comment]
Is there still interested in moving to v2? If it is so, I would like to help. Should I open a PR?

**Comment by boesing** [comment]
@gennadigennadigennadi Sure!

**Comment by gennadigennadigennadi** [comment]
@boesing Target Branch is master?

**Comment by boesing** [comment]
@gennadigennadigennadi 3.2.x as we switched to `laminas/automatic-releases` 👍
