### ISSUE TITLE
 Breakage with latest servicemanager and psr/container v2 #92 

### ISSUE THREAD

**Issue by remicollet** [laminas/laminas-di#78]
Running laminas-servicemanager-di test suite

`PHP Fatal error:  Declaration of Laminas\Di\Di::has($name) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /usr/share/php/Laminas/Di/Di.php on line 220
`

**Comment by Ocramius** [comment]
Ref: https://github.com/laminas/laminas-servicemanager/pull/147

**Comment by Ocramius** [comment]
https://github.com/laminas/laminas-servicemanager/releases/tag/3.15.1 should fix this: sad to see that work reverted, but our hopes that it would work were unfounded.
