### ISSUE TITLE
Wrong handling of versions in documentation

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-di#8]
### Bug Report

Different versions can be handled by our documentation theme.

laminas-hydrator use different versions in documentation already:
https://github.com/laminas/laminas-hydrator/blob/02a5cfdc0dbf2b9abbe7aca3472de514d10e2d6b/mkdocs.yml#L6-L27

**Comment by tux-rampage** [comment]
So can we drop the `v2` section and move `v3` to the main level? Would be great.
I guess this is a leftover from ZF docs.
